# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Set working directory
WORKDIR /app

# Copy package files
COPY package.json package-lock.json* ./

# Install dependencies
RUN npm install --ignore-scripts

# Copy the rest of the source code
COPY . .

# Build the project
RUN npm run build

# Expose port
EXPOSE 3000

# Use run-with-env.js as the entrypoint to ensure proper environment loading and transport argument
CMD [ "node", "run-with-env.js" ]
